dist: trusty
sudo: required
group: edge
language: node_js
node_js:
  - "7"
addons:
  chrome: stable
branches:
  only:
    - master
    - develop
git:
  depth: 3
notifications:
  email:
    recipients:
      - platform@veo-labs.com
    on_success: always
    on_failure: always
before_install:
  - rvm install ruby-latest
  - npm install -g grunt-cli
  - gem install sass
  - gem install compass
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - npm install --ignore-scripts
  - grunt dist
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - grunt karma
